package com.orgmemory.core.permission;

public enum PermissionReason {
    INVALID_REQUEST,
    INACTIVE_SUBJECT,
    ORGANIZATION_MISMATCH,
    SOURCE_PERMISSION_DENIED,
    SOURCE_PERMISSION_UNKNOWN,
    ORGMEMORY_PERMISSION_DENIED,
    ORGMEMORY_PERMISSION_UNKNOWN,
    CLASSIFICATION_MISSING,
    DECLARED_ACCESS_MISSING,
    DECLARED_ACCESS_MISMATCH,
    SUBJECT_ROLE_MISSING,
    SUBJECT_DEPARTMENT_MISSING,
    RESOURCE_DEPARTMENT_MISSING,
    PUBLIC_ACCESS,
    INTERNAL_ACCESS,
    CONFIDENTIAL_SAME_DEPARTMENT,
    CONFIDENTIAL_OTHER_DEPARTMENT,
    CONFIDENTIAL_EXECUTIVE,
    RESTRICTED_NON_EXECUTIVE,
    RESTRICTED_EXECUTIVE
}
