/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminMappingsRouteImport } from './routes/admin/mappings'
import { Route as AdminScimRouteImport } from './routes/admin/scim'
import { Route as AdminConnectorsIndexRouteImport } from './routes/admin/connectors/index'
import { Route as AdminConnectorsNewRouteImport } from './routes/admin/connectors/new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminConnectorsSourceSystemIndexRouteImport } from './routes/admin/connectors/$sourceSystem.index'
import { Route as AdminConnectorsSourceSystemConnectionKeyRouteImport } from './routes/admin/connectors/$sourceSystem.$connectionKey'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMappingsRoute = AdminMappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScimRoute = AdminScimRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsIndexRoute = AdminConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsNewRoute = AdminConnectorsNewRouteImport.update({
  id: '/connectors/new',
  path: '/connectors/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsSourceSystemIndexRoute =
  AdminConnectorsSourceSystemIndexRouteImport.update({
    id: '/connectors/$sourceSystem/',
    path: '/connectors/$sourceSystem/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConnectorsSourceSystemConnectionKeyRoute =
  AdminConnectorsSourceSystemConnectionKeyRouteImport.update({
    id: '/connectors/$sourceSystem/$connectionKey',
    path: '/connectors/$sourceSystem/$connectionKey',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/connectors/': typeof AdminConnectorsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/connectors/$sourceSystem/$connectionKey': typeof AdminConnectorsSourceSystemConnectionKeyRoute
  '/admin/connectors/$sourceSystem/': typeof AdminConnectorsSourceSystemIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/connectors': typeof AdminConnectorsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/connectors/$sourceSystem/$connectionKey': typeof AdminConnectorsSourceSystemConnectionKeyRoute
  '/admin/connectors/$sourceSystem': typeof AdminConnectorsSourceSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/connectors/': typeof AdminConnectorsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/connectors/$sourceSystem/$connectionKey': typeof AdminConnectorsSourceSystemConnectionKeyRoute
  '/admin/connectors/$sourceSystem/': typeof AdminConnectorsSourceSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sources'
    | '/admin/access'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/admin/'
    | '/admin/connectors/new'
    | '/admin/users/$userId'
    | '/admin/connectors/'
    | '/admin/users/'
    | '/admin/connectors/$sourceSystem/$connectionKey'
    | '/admin/connectors/$sourceSystem/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sources'
    | '/admin/access'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/'
    | '/admin'
    | '/admin/connectors/new'
    | '/admin/users/$userId'
    | '/admin/connectors'
    | '/admin/users'
    | '/admin/connectors/$sourceSystem/$connectionKey'
    | '/admin/connectors/$sourceSystem'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/_authenticated/sources'
    | '/admin/access'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/_authenticated/'
    | '/admin/'
    | '/admin/connectors/new'
    | '/admin/users/$userId'
    | '/admin/connectors/'
    | '/admin/users/'
    | '/admin/connectors/$sourceSystem/$connectionKey'
    | '/admin/connectors/$sourceSystem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mappings': {
      id: '/admin/mappings'
      path: '/mappings'
      fullPath: '/admin/mappings'
      preLoaderRoute: typeof AdminMappingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scim': {
      id: '/admin/scim'
      path: '/scim'
      fullPath: '/admin/scim'
      preLoaderRoute: typeof AdminScimRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/': {
      id: '/admin/connectors/'
      path: '/connectors'
      fullPath: '/admin/connectors/'
      preLoaderRoute: typeof AdminConnectorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/new': {
      id: '/admin/connectors/new'
      path: '/connectors/new'
      fullPath: '/admin/connectors/new'
      preLoaderRoute: typeof AdminConnectorsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/$sourceSystem/': {
      id: '/admin/connectors/$sourceSystem/'
      path: '/connectors/$sourceSystem'
      fullPath: '/admin/connectors/$sourceSystem/'
      preLoaderRoute: typeof AdminConnectorsSourceSystemIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/$sourceSystem/$connectionKey': {
      id: '/admin/connectors/$sourceSystem/$connectionKey'
      path: '/connectors/$sourceSystem/$connectionKey'
      fullPath: '/admin/connectors/$sourceSystem/$connectionKey'
      preLoaderRoute: typeof AdminConnectorsSourceSystemConnectionKeyRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMappingsRoute: typeof AdminMappingsRoute
  AdminScimRoute: typeof AdminScimRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConnectorsNewRoute: typeof AdminConnectorsNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminConnectorsIndexRoute: typeof AdminConnectorsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminConnectorsSourceSystemConnectionKeyRoute: typeof AdminConnectorsSourceSystemConnectionKeyRoute
  AdminConnectorsSourceSystemIndexRoute: typeof AdminConnectorsSourceSystemIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMappingsRoute: AdminMappingsRoute,
  AdminScimRoute: AdminScimRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConnectorsNewRoute: AdminConnectorsNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminConnectorsIndexRoute: AdminConnectorsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminConnectorsSourceSystemConnectionKeyRoute:
    AdminConnectorsSourceSystemConnectionKeyRoute,
  AdminConnectorsSourceSystemIndexRoute: AdminConnectorsSourceSystemIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
