/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminMappingsRouteImport } from './routes/admin/mappings'
import { Route as AdminScimRouteImport } from './routes/admin/scim'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminConnectorsIndexRouteImport } from './routes/admin/connectors/index'
import { Route as AdminConnectorsNewRouteImport } from './routes/admin/connectors/new'
import { Route as AdminConnectorsSlackRouteImport } from './routes/admin/connectors/slack'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMappingsRoute = AdminMappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScimRoute = AdminScimRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsIndexRoute = AdminConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsNewRoute = AdminConnectorsNewRouteImport.update({
  id: '/connectors/new',
  path: '/connectors/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsSlackRoute = AdminConnectorsSlackRouteImport.update({
  id: '/connectors/slack',
  path: '/connectors/slack',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/connectors/slack': typeof AdminConnectorsSlackRoute
  '/admin/connectors/': typeof AdminConnectorsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/connectors/slack': typeof AdminConnectorsSlackRoute
  '/admin/connectors': typeof AdminConnectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/mappings': typeof AdminMappingsRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/users': typeof AdminUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/connectors/new': typeof AdminConnectorsNewRoute
  '/admin/connectors/slack': typeof AdminConnectorsSlackRoute
  '/admin/connectors/': typeof AdminConnectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sources'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/admin/users'
    | '/admin/'
    | '/admin/connectors/new'
    | '/admin/connectors/slack'
    | '/admin/connectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sources'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/admin/connectors/new'
    | '/admin/connectors/slack'
    | '/admin/connectors'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/_authenticated/sources'
    | '/admin/groups'
    | '/admin/mappings'
    | '/admin/scim'
    | '/admin/users'
    | '/_authenticated/'
    | '/admin/'
    | '/admin/connectors/new'
    | '/admin/connectors/slack'
    | '/admin/connectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mappings': {
      id: '/admin/mappings'
      path: '/mappings'
      fullPath: '/admin/mappings'
      preLoaderRoute: typeof AdminMappingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scim': {
      id: '/admin/scim'
      path: '/scim'
      fullPath: '/admin/scim'
      preLoaderRoute: typeof AdminScimRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/': {
      id: '/admin/connectors/'
      path: '/connectors'
      fullPath: '/admin/connectors/'
      preLoaderRoute: typeof AdminConnectorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/new': {
      id: '/admin/connectors/new'
      path: '/connectors/new'
      fullPath: '/admin/connectors/new'
      preLoaderRoute: typeof AdminConnectorsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors/slack': {
      id: '/admin/connectors/slack'
      path: '/connectors/slack'
      fullPath: '/admin/connectors/slack'
      preLoaderRoute: typeof AdminConnectorsSlackRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminMappingsRoute: typeof AdminMappingsRoute
  AdminScimRoute: typeof AdminScimRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConnectorsNewRoute: typeof AdminConnectorsNewRoute
  AdminConnectorsSlackRoute: typeof AdminConnectorsSlackRoute
  AdminConnectorsIndexRoute: typeof AdminConnectorsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGroupsRoute: AdminGroupsRoute,
  AdminMappingsRoute: AdminMappingsRoute,
  AdminScimRoute: AdminScimRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConnectorsNewRoute: AdminConnectorsNewRoute,
  AdminConnectorsSlackRoute: AdminConnectorsSlackRoute,
  AdminConnectorsIndexRoute: AdminConnectorsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
